CUDA_VISIBLE_DEVICES=1 python ../intervention_genes/template_genes.py \
    --one_shot_root '../Data/Source_Data/One_Shot_Cases/Test_set' \
    --zero_shot_root '../Data/Source_Data/Zero_Shot_Cases/Test_set' \
    --lang_pairs 'en-zh' \
    --subset_root_save '../Detect_Data/genes' \
    --subset_eval_save '../Detect_Data/evals' \
    --model_name 'llama2-7b-hf' \
    --device 'cuda' \
    --batch_size 2 \
    --max_token 400 \
    --template_type 'temp3' \
    --heads_type 'abla-temp3' \
    --file_type 'Test' \
    --shot_setting 'one,zero'